---
- include_role:
    name: microk8s

- include_role:
    name: dt-operator
  vars:
    operator_mode: "applicationMonitoring" 
- include_role:
    name: app-unguard
- include_role:
    name: app-glpi

