apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glpi-ingress
  namespace: glpi 
  annotations: 
    # cert-manager.io/issuer: "letsencrypt-staging"
    cert-manager.io/issuer: "letsencrypt-prod"

spec:
  ingressClassName: traefik
  tls: 
  - hosts: 
    - {{ .Chart.Name }}.{{ .Values.ingress.domain }}
    secretName: glpi-tls
  rules:
  - host: {{ .Chart.Name }}.{{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
